### ISSUE TITLE
Can't find the package.....

### ISSUE THREAD

**Issue by FVI812** [anynon/HideLabels13#2]
Hey guys, here's the screenshot of what u get trying to install it.

![EB01857F-9257-4507-A728-B92819AC146C](https://user-images.githubusercontent.com/20651319/75166813-74362000-56f2-11ea-9a5e-56cae8c026a5.png)

**Comment by anynon** [comment]
Refreshing your sources should solve this issue. If not, re-adding the Packix repo or using a different package manager should work.
